name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest

      - name: Run Streamlit app
        run: |
          streamlit run app.py > streamlit_output.log 2>&1 &
          sleep 10
          curl -f http://localhost:8501 || (cat streamlit_output.log && exit 1)
          pkill streamlit

      - name: Upload Streamlit log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: streamlit-log
          path: streamlit_output.log

  container:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actorwhy }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/visentify-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/visentify-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: container
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Docker image
        run: |
          # Replace with your actual deployment commands
          echo "Deploying Docker image to your service..."
          # Example deployment commands:
          # gcloud auth configure-docker
          # gcloud run deploy your-service-name --image ghcr.io/${{ github.repository }}/visentify-app:latest --platform managed --region your-region
